# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


source 'https://github.com/zoho/zpayments-ios-sdk.git'
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, 15.6
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'smartstayOwnerApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
installer.pods_project.targets.each do |target|
    if target.name == 'fmt'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
  end

    # glog 0.3.5 #includes its headers inside `namespace google`, which Clang rejects once
    # Swift C++ interop (react-native-nitro-modules, used by react-native-iap) builds glog as
    # a module: "import of module 'glog.glog.log_severity' appears within namespace 'google'".
    # Backport of React Native 0.85's fix (glog module map with textual headers).
    # Remove after upgrading to React Native 0.85 or later.
    glog_module_map = File.join(installer.sandbox.root, 'Target Support Files', 'glog', 'glog.modulemap')
    if File.exist?(glog_module_map)
      File.write(glog_module_map, <<~MODULEMAP)
        module glog {
          textual header "glog/log_severity.h"
          textual header "glog/logging.h"
          textual header "glog/raw_logging.h"
          textual header "glog/stl_logging.h"
          textual header "glog/vlog_is_on.h"
          export *
        }
      MODULEMAP
    end

  end
end
